// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: realtimeanalytics/v1/realtimeanalytics.proto

package realtimeanalyticsv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"

	v1 "github.com/percona/pmm/api/inventory/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RunningRealtimeAgent represents a currently running RTA agent.
type RunningRealtimeAgent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique agent identifier.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Service identifier that the agent is monitoring.
	ServiceId string `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	// Service name.
	ServiceName string `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Cluster name the service belongs to.
	Cluster string `protobuf:"bytes,4,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// Timestamp when the agent was started.
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// Current status of the agent.
	Status        v1.AgentStatus `protobuf:"varint,6,opt,name=status,proto3,enum=inventory.v1.AgentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunningRealtimeAgent) Reset() {
	*x = RunningRealtimeAgent{}
	mi := &file_realtimeanalytics_v1_realtimeanalytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunningRealtimeAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningRealtimeAgent) ProtoMessage() {}

func (x *RunningRealtimeAgent) ProtoReflect() protoreflect.Message {
	mi := &file_realtimeanalytics_v1_realtimeanalytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningRealtimeAgent.ProtoReflect.Descriptor instead.
func (*RunningRealtimeAgent) Descriptor() ([]byte, []int) {
	return file_realtimeanalytics_v1_realtimeanalytics_proto_rawDescGZIP(), []int{0}
}

func (x *RunningRealtimeAgent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RunningRealtimeAgent) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *RunningRealtimeAgent) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RunningRealtimeAgent) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *RunningRealtimeAgent) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *RunningRealtimeAgent) GetStatus() v1.AgentStatus {
	if x != nil {
		return x.Status
	}
	return v1.AgentStatus(0)
}

// ListRunningRealtimeAgentsRequest contains optional filters for listing running RTA agents.
type ListRunningRealtimeAgentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter by cluster name.
	Cluster       string `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunningRealtimeAgentsRequest) Reset() {
	*x = ListRunningRealtimeAgentsRequest{}
	mi := &file_realtimeanalytics_v1_realtimeanalytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunningRealtimeAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunningRealtimeAgentsRequest) ProtoMessage() {}

func (x *ListRunningRealtimeAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realtimeanalytics_v1_realtimeanalytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunningRealtimeAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListRunningRealtimeAgentsRequest) Descriptor() ([]byte, []int) {
	return file_realtimeanalytics_v1_realtimeanalytics_proto_rawDescGZIP(), []int{1}
}

func (x *ListRunningRealtimeAgentsRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

// ListRunningRealtimeAgentsResponse returns the list of running RTA agents.
type ListRunningRealtimeAgentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of running RTA agents.
	Agents        []*RunningRealtimeAgent `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunningRealtimeAgentsResponse) Reset() {
	*x = ListRunningRealtimeAgentsResponse{}
	mi := &file_realtimeanalytics_v1_realtimeanalytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunningRealtimeAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunningRealtimeAgentsResponse) ProtoMessage() {}

func (x *ListRunningRealtimeAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realtimeanalytics_v1_realtimeanalytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunningRealtimeAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListRunningRealtimeAgentsResponse) Descriptor() ([]byte, []int) {
	return file_realtimeanalytics_v1_realtimeanalytics_proto_rawDescGZIP(), []int{2}
}

func (x *ListRunningRealtimeAgentsResponse) GetAgents() []*RunningRealtimeAgent {
	if x != nil {
		return x.Agents
	}
	return nil
}

// ChangeRealtimeAnalyticsRequest contains parameters for enabling or disabling RTA.
type ChangeRealtimeAnalyticsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enable or disable RTA.
	Enable bool `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	// Service identifier.
	ServiceId     string `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeRealtimeAnalyticsRequest) Reset() {
	*x = ChangeRealtimeAnalyticsRequest{}
	mi := &file_realtimeanalytics_v1_realtimeanalytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeRealtimeAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRealtimeAnalyticsRequest) ProtoMessage() {}

func (x *ChangeRealtimeAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realtimeanalytics_v1_realtimeanalytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRealtimeAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*ChangeRealtimeAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_realtimeanalytics_v1_realtimeanalytics_proto_rawDescGZIP(), []int{3}
}

func (x *ChangeRealtimeAnalyticsRequest) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *ChangeRealtimeAnalyticsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

// ChangeRealtimeAnalyticsResponse is the response for changing RTA configuration.
type ChangeRealtimeAnalyticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeRealtimeAnalyticsResponse) Reset() {
	*x = ChangeRealtimeAnalyticsResponse{}
	mi := &file_realtimeanalytics_v1_realtimeanalytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeRealtimeAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRealtimeAnalyticsResponse) ProtoMessage() {}

func (x *ChangeRealtimeAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realtimeanalytics_v1_realtimeanalytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRealtimeAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*ChangeRealtimeAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_realtimeanalytics_v1_realtimeanalytics_proto_rawDescGZIP(), []int{4}
}

// QueryDataItem represents a single query in real-time analytics data.
type QueryDataItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique query identifier.
	QueryId string `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	// Service identifier.
	ServiceId string `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	// Service name.
	ServiceName string `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Cluster name.
	Cluster string `protobuf:"bytes,4,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// Database namespace (database.collection).
	Namespace string `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Raw query JSON.
	Query string `protobuf:"bytes,6,opt,name=query,proto3" json:"query,omitempty"`
	// Query fingerprint.
	Fingerprint string `protobuf:"bytes,7,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	// Query duration in milliseconds.
	Duration float64 `protobuf:"fixed64,8,opt,name=duration,proto3" json:"duration,omitempty"`
	// Timestamp when the query was captured.
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDataItem) Reset() {
	*x = QueryDataItem{}
	mi := &file_realtimeanalytics_v1_realtimeanalytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDataItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDataItem) ProtoMessage() {}

func (x *QueryDataItem) ProtoReflect() protoreflect.Message {
	mi := &file_realtimeanalytics_v1_realtimeanalytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDataItem.ProtoReflect.Descriptor instead.
func (*QueryDataItem) Descriptor() ([]byte, []int) {
	return file_realtimeanalytics_v1_realtimeanalytics_proto_rawDescGZIP(), []int{5}
}

func (x *QueryDataItem) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryDataItem) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *QueryDataItem) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *QueryDataItem) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *QueryDataItem) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *QueryDataItem) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryDataItem) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *QueryDataItem) GetDuration() float64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *QueryDataItem) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// GetRealtimeQueryDataRequest contains filters for fetching real-time query data.
type GetRealtimeQueryDataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional list of service IDs to filter by (OR logic).
	// If empty, returns data for all services.
	ServiceIds    []string `protobuf:"bytes,1,rep,name=service_ids,json=serviceIds,proto3" json:"service_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRealtimeQueryDataRequest) Reset() {
	*x = GetRealtimeQueryDataRequest{}
	mi := &file_realtimeanalytics_v1_realtimeanalytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealtimeQueryDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealtimeQueryDataRequest) ProtoMessage() {}

func (x *GetRealtimeQueryDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_realtimeanalytics_v1_realtimeanalytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealtimeQueryDataRequest.ProtoReflect.Descriptor instead.
func (*GetRealtimeQueryDataRequest) Descriptor() ([]byte, []int) {
	return file_realtimeanalytics_v1_realtimeanalytics_proto_rawDescGZIP(), []int{6}
}

func (x *GetRealtimeQueryDataRequest) GetServiceIds() []string {
	if x != nil {
		return x.ServiceIds
	}
	return nil
}

// GetRealtimeQueryDataResponse returns real-time query data.
type GetRealtimeQueryDataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of query data items.
	Queries       []*QueryDataItem `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRealtimeQueryDataResponse) Reset() {
	*x = GetRealtimeQueryDataResponse{}
	mi := &file_realtimeanalytics_v1_realtimeanalytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRealtimeQueryDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRealtimeQueryDataResponse) ProtoMessage() {}

func (x *GetRealtimeQueryDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_realtimeanalytics_v1_realtimeanalytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRealtimeQueryDataResponse.ProtoReflect.Descriptor instead.
func (*GetRealtimeQueryDataResponse) Descriptor() ([]byte, []int) {
	return file_realtimeanalytics_v1_realtimeanalytics_proto_rawDescGZIP(), []int{7}
}

func (x *GetRealtimeQueryDataResponse) GetQueries() []*QueryDataItem {
	if x != nil {
		return x.Queries
	}
	return nil
}

var File_realtimeanalytics_v1_realtimeanalytics_proto protoreflect.FileDescriptor

const file_realtimeanalytics_v1_realtimeanalytics_proto_rawDesc = "" +
	"\n" +
	",realtimeanalytics/v1/realtimeanalytics.proto\x12\x14realtimeanalytics.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1finventory/v1/agent_status.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17validate/validate.proto\"\xfb\x01\n" +
	"\x14RunningRealtimeAgent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x18\n" +
	"\acluster\x18\x04 \x01(\tR\acluster\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x121\n" +
	"\x06status\x18\x06 \x01(\x0e2\x19.inventory.v1.AgentStatusR\x06status\"<\n" +
	" ListRunningRealtimeAgentsRequest\x12\x18\n" +
	"\acluster\x18\x01 \x01(\tR\acluster\"g\n" +
	"!ListRunningRealtimeAgentsResponse\x12B\n" +
	"\x06agents\x18\x01 \x03(\v2*.realtimeanalytics.v1.RunningRealtimeAgentR\x06agents\"`\n" +
	"\x1eChangeRealtimeAnalyticsRequest\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\x12&\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\tserviceId\"!\n" +
	"\x1fChangeRealtimeAnalyticsResponse\"\xb2\x02\n" +
	"\rQueryDataItem\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x18\n" +
	"\acluster\x18\x04 \x01(\tR\acluster\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05query\x18\x06 \x01(\tR\x05query\x12 \n" +
	"\vfingerprint\x18\a \x01(\tR\vfingerprint\x12\x1a\n" +
	"\bduration\x18\b \x01(\x01R\bduration\x128\n" +
	"\ttimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\">\n" +
	"\x1bGetRealtimeQueryDataRequest\x12\x1f\n" +
	"\vservice_ids\x18\x01 \x03(\tR\n" +
	"serviceIds\"]\n" +
	"\x1cGetRealtimeQueryDataResponse\x12=\n" +
	"\aqueries\x18\x01 \x03(\v2#.realtimeanalytics.v1.QueryDataItemR\aqueries2\xd5\a\n" +
	"\x18RealtimeAnalyticsService\x12\xdc\x02\n" +
	"\x19ListRunningRealtimeAgents\x126.realtimeanalytics.v1.ListRunningRealtimeAgentsRequest\x1a7.realtimeanalytics.v1.ListRunningRealtimeAgentsResponse\"\xcd\x01\x92A\xae\x01\x12\x17List Running RTA Agents\x1a\x92\x01Returns the list of all currently running Real-Time Analytics agents with their details including service, cluster, agent, and status information.\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/realtime/agents\x12\x95\x02\n" +
	"\x17ChangeRealtimeAnalytics\x124.realtimeanalytics.v1.ChangeRealtimeAnalyticsRequest\x1a5.realtimeanalytics.v1.ChangeRealtimeAnalyticsResponse\"\x8c\x01\x92Ak\x12(Change Real-Time Analytics Configuration\x1a?Enables or disables Real-Time Analytics for a specific service.\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/realtime/change\x12\xc1\x02\n" +
	"\x14GetRealtimeQueryData\x121.realtimeanalytics.v1.GetRealtimeQueryDataRequest\x1a2.realtimeanalytics.v1.GetRealtimeQueryDataResponse\"\xc1\x01\x92A\x9e\x01\x12\x18Get Real-Time Query Data\x1a\x81\x01Returns real-time query data from the in-memory store. Supports filtering by service IDs. Designed for short polling from the UI.\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/realtime/query-dataB\xe8\x01\n" +
	"\x18com.realtimeanalytics.v1B\x16RealtimeanalyticsProtoP\x01ZCgithub.com/percona/pmm/api/realtimeanalytics/v1;realtimeanalyticsv1\xa2\x02\x03RXX\xaa\x02\x14Realtimeanalytics.V1\xca\x02\x14Realtimeanalytics\\V1\xe2\x02 Realtimeanalytics\\V1\\GPBMetadata\xea\x02\x15Realtimeanalytics::V1b\x06proto3"

var (
	file_realtimeanalytics_v1_realtimeanalytics_proto_rawDescOnce sync.Once
	file_realtimeanalytics_v1_realtimeanalytics_proto_rawDescData []byte
)

func file_realtimeanalytics_v1_realtimeanalytics_proto_rawDescGZIP() []byte {
	file_realtimeanalytics_v1_realtimeanalytics_proto_rawDescOnce.Do(func() {
		file_realtimeanalytics_v1_realtimeanalytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_realtimeanalytics_v1_realtimeanalytics_proto_rawDesc), len(file_realtimeanalytics_v1_realtimeanalytics_proto_rawDesc)))
	})
	return file_realtimeanalytics_v1_realtimeanalytics_proto_rawDescData
}

var (
	file_realtimeanalytics_v1_realtimeanalytics_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
	file_realtimeanalytics_v1_realtimeanalytics_proto_goTypes  = []any{
		(*RunningRealtimeAgent)(nil),              // 0: realtimeanalytics.v1.RunningRealtimeAgent
		(*ListRunningRealtimeAgentsRequest)(nil),  // 1: realtimeanalytics.v1.ListRunningRealtimeAgentsRequest
		(*ListRunningRealtimeAgentsResponse)(nil), // 2: realtimeanalytics.v1.ListRunningRealtimeAgentsResponse
		(*ChangeRealtimeAnalyticsRequest)(nil),    // 3: realtimeanalytics.v1.ChangeRealtimeAnalyticsRequest
		(*ChangeRealtimeAnalyticsResponse)(nil),   // 4: realtimeanalytics.v1.ChangeRealtimeAnalyticsResponse
		(*QueryDataItem)(nil),                     // 5: realtimeanalytics.v1.QueryDataItem
		(*GetRealtimeQueryDataRequest)(nil),       // 6: realtimeanalytics.v1.GetRealtimeQueryDataRequest
		(*GetRealtimeQueryDataResponse)(nil),      // 7: realtimeanalytics.v1.GetRealtimeQueryDataResponse
		(*timestamppb.Timestamp)(nil),             // 8: google.protobuf.Timestamp
		(v1.AgentStatus)(0),                       // 9: inventory.v1.AgentStatus
	}
)

var file_realtimeanalytics_v1_realtimeanalytics_proto_depIdxs = []int32{
	8, // 0: realtimeanalytics.v1.RunningRealtimeAgent.started_at:type_name -> google.protobuf.Timestamp
	9, // 1: realtimeanalytics.v1.RunningRealtimeAgent.status:type_name -> inventory.v1.AgentStatus
	0, // 2: realtimeanalytics.v1.ListRunningRealtimeAgentsResponse.agents:type_name -> realtimeanalytics.v1.RunningRealtimeAgent
	8, // 3: realtimeanalytics.v1.QueryDataItem.timestamp:type_name -> google.protobuf.Timestamp
	5, // 4: realtimeanalytics.v1.GetRealtimeQueryDataResponse.queries:type_name -> realtimeanalytics.v1.QueryDataItem
	1, // 5: realtimeanalytics.v1.RealtimeAnalyticsService.ListRunningRealtimeAgents:input_type -> realtimeanalytics.v1.ListRunningRealtimeAgentsRequest
	3, // 6: realtimeanalytics.v1.RealtimeAnalyticsService.ChangeRealtimeAnalytics:input_type -> realtimeanalytics.v1.ChangeRealtimeAnalyticsRequest
	6, // 7: realtimeanalytics.v1.RealtimeAnalyticsService.GetRealtimeQueryData:input_type -> realtimeanalytics.v1.GetRealtimeQueryDataRequest
	2, // 8: realtimeanalytics.v1.RealtimeAnalyticsService.ListRunningRealtimeAgents:output_type -> realtimeanalytics.v1.ListRunningRealtimeAgentsResponse
	4, // 9: realtimeanalytics.v1.RealtimeAnalyticsService.ChangeRealtimeAnalytics:output_type -> realtimeanalytics.v1.ChangeRealtimeAnalyticsResponse
	7, // 10: realtimeanalytics.v1.RealtimeAnalyticsService.GetRealtimeQueryData:output_type -> realtimeanalytics.v1.GetRealtimeQueryDataResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_realtimeanalytics_v1_realtimeanalytics_proto_init() }
func file_realtimeanalytics_v1_realtimeanalytics_proto_init() {
	if File_realtimeanalytics_v1_realtimeanalytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_realtimeanalytics_v1_realtimeanalytics_proto_rawDesc), len(file_realtimeanalytics_v1_realtimeanalytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_realtimeanalytics_v1_realtimeanalytics_proto_goTypes,
		DependencyIndexes: file_realtimeanalytics_v1_realtimeanalytics_proto_depIdxs,
		MessageInfos:      file_realtimeanalytics_v1_realtimeanalytics_proto_msgTypes,
	}.Build()
	File_realtimeanalytics_v1_realtimeanalytics_proto = out.File
	file_realtimeanalytics_v1_realtimeanalytics_proto_goTypes = nil
	file_realtimeanalytics_v1_realtimeanalytics_proto_depIdxs = nil
}
